/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.staff.view;

import com.staff.controller.StaffController;
import com.staff.model.Staff;
import static com.sun.org.apache.xalan.internal.xsltc.compiler.util.Type.String;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sanja_000
 */
public class AddStaff extends javax.swing.JInternalFrame {

   DefaultTableModel model;
    private SimpleDateFormat SimpleDateFormat;

    /**
     * Creates new form AddStaff
     */
    public AddStaff() {
         initComponents();
         //setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);
        model = new DefaultTableModel(null,new String[]{"Id","FullName","Address","Dob","Doj","Designation","Contact No","BankAccNo","BasicSalary"});
        jTable_staff.setModel(model);
    }

    private void clearField()
    {
        //jTextField_dob.setText(""); 
        //jTextField_doj.getDate("")toString();
        jLabel9_id.setText("");
        jTextField_fullName.setText("");
        jTextField_address.setText("");
        jTextField_combo.setText("");
        jTextField_contactNo.setText("");
        jTextField_bankAccNo.setText("");
       
        jTextField_basicSalary.setText("");
    }
    private void clearTable()
    {
        int count = jTable_staff.getRowCount();
        for(int i=0;i<count;i++)
        {
           model.removeRow(0);
        }
        //clearField();
    }
     
     private void loadData()
    {
         clearTable();
        StaffController sc=new StaffController();
        ArrayList<Staff> list=sc.fetchData();
        
        for(int i=0;i<list.size();i++)
        {
            model.addRow(new Object[]
            {
            list.get(i).getStaffId(),
            list.get(i).getFullName(),
            list.get(i).getAddress(),
            list.get(i).getDob(),
            list.get(i).getDoj(),
            list.get(i).getDesignation(),
            list.get(i).getContactNo(),
            list.get(i).getBankAccNo(),
            list.get(i).getBasicSalary()});
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField_fullName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_address = new javax.swing.JTextField();
        jButton_save = new javax.swing.JButton();
        jButton_update = new javax.swing.JButton();
        jButton_delete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_contactNo = new javax.swing.JTextField();
        jTextField_bankAccNo = new javax.swing.JTextField();
        jTextField_basicSalary = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_staff = new javax.swing.JTable();
        jButton_loadStaff = new javax.swing.JButton();
        jComboBox_designation = new javax.swing.JComboBox<>();
        jLabel = new javax.swing.JLabel();
        jLabel9_id = new javax.swing.JLabel();
        jTextField_doj = new com.toedter.calendar.JDateChooser();
        jTextField_dob = new com.toedter.calendar.JDateChooser();
        jTextField_combo = new javax.swing.JTextField();
        jButton_clearField = new javax.swing.JButton();
        jLabel_cerror = new javax.swing.JLabel();
        jLabel_cerr = new javax.swing.JLabel();
        jLabel_bank = new javax.swing.JLabel();
        jLabel_b = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Add Staff Record");
        setMinimumSize(new java.awt.Dimension(1364, 762));

        jLabel1.setText("Full Name");

        jTextField_fullName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_fullNameActionPerformed(evt);
            }
        });
        jTextField_fullName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_fullNameKeyTyped(evt);
            }
        });

        jLabel2.setText("Address");

        jButton_save.setText("Save");
        jButton_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveActionPerformed(evt);
            }
        });

        jButton_update.setText("Update");
        jButton_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_updateActionPerformed(evt);
            }
        });

        jButton_delete.setText("Delete");
        jButton_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_deleteActionPerformed(evt);
            }
        });

        jLabel3.setText("DOB");

        jLabel4.setText("DOJ");

        jLabel5.setText("Designation");

        jLabel6.setText("Contact No");

        jLabel7.setText("BankACCNo");

        jLabel8.setText("Basic Salary");

        jTextField_contactNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_contactNoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_contactNoKeyTyped(evt);
            }
        });

        jTextField_bankAccNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_bankAccNoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_bankAccNoKeyTyped(evt);
            }
        });

        jTextField_basicSalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_basicSalaryKeyTyped(evt);
            }
        });

        jTable_staff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_staff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_staffMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_staff);

        jButton_loadStaff.setText("Load Data");
        jButton_loadStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loadStaffActionPerformed(evt);
            }
        });

        jComboBox_designation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teaching Staff", "Non Teaching Staff" }));
        jComboBox_designation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_designationActionPerformed(evt);
            }
        });

        jLabel.setText("ID");

        jTextField_doj.setMaxSelectableDate(new java.util.Date(1514661401000L));
        jTextField_doj.setMinSelectableDate(new java.util.Date(1262287001000L));

        jTextField_dob.setMaxSelectableDate(new java.util.Date(883595769000L));
        jTextField_dob.setMinSelectableDate(new java.util.Date(-946787331000L));

        jButton_clearField.setText("Clear");
        jButton_clearField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_clearFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_save)
                        .addGap(33, 33, 33)
                        .addComponent(jButton_update)
                        .addGap(36, 36, 36)
                        .addComponent(jButton_delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 502, Short.MAX_VALUE)
                        .addComponent(jButton_loadStaff)
                        .addGap(65, 65, 65)
                        .addComponent(jButton_clearField)
                        .addGap(305, 305, 305))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField_dob, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_doj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox_designation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_fullName, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(jTextField_address)
                                    .addComponent(jTextField_contactNo)
                                    .addComponent(jTextField_bankAccNo)
                                    .addComponent(jTextField_basicSalary)
                                    .addComponent(jLabel9_id))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(jLabel_b, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel_bank)
                                                .addGap(46, 46, 46)
                                                .addComponent(jLabel_cerr)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel_cerror))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel)
                            .addComponent(jLabel9_id))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_fullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextField_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addComponent(jLabel3)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_doj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox_designation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField_contactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_cerror)
                            .addComponent(jLabel_cerr))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jTextField_bankAccNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_b)
                                .addComponent(jLabel9))
                            .addComponent(jLabel_bank, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField_basicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_save)
                            .addComponent(jButton_update)
                            .addComponent(jButton_delete)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_loadStaff)
                            .addComponent(jButton_clearField))))
                .addContainerGap(245, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveActionPerformed
        // TODO add your handling code here:
        
       String err="";
        if(jTextField_fullName.getText().equals("")||jTextField_address.getText().equals("")||jTextField_contactNo.getText().equals("")
             ||jTextField_combo.getText().equals("")||jTextField_bankAccNo.getText().equals("")||jTextField_basicSalary.getText().equals("")
                ||jTextField_contactNo.getText().equals("")||jTextField_dob.getDate().equals("")||jTextField_doj.getDate().equals(""))
        {
            err+="err";
        }
        if(err.equals(""))
        {
         Staff ob=new Staff();
       SimpleDateFormat dFormat;
       SimpleDateFormat = dFormat =new SimpleDateFormat("yyyy-MM-dd");
        String dob=dFormat.format(jTextField_dob.getDate()); 
        String doj=dFormat.format(jTextField_doj.getDate());
        ob.setFullName(jTextField_fullName.getText());
        ob.setAddress(jTextField_address.getText());
        //ob.setDob(jTextField_dob.getSelectedValue().toString());
        //ob.setDoj(jTextField_doj.getSelectedDate().toString());
        ob.setDob(dob);
        ob.setDoj(doj);
        ob.setDesignation(jTextField_combo.getText().toString());
        ob.setContactNo(Long.parseLong(jTextField_contactNo.getText()));
        /*String PATTERN="\\d{10}";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(jTextField_contactNo.getText());
        if(!match.matches())
        {
            jLabel_cerr.setText("Invalid");
        }
        else
        {
            jLabel_cerr.setText(null);
        }
        */
        ob.setBankAccNo(Long.parseLong(jTextField_bankAccNo.getText()));
       
        double salary=Double.parseDouble(jTextField_basicSalary.getText());
        ob.setBasicSalary(salary);
        StaffController sc=new StaffController();
        sc.addStaff(ob);
        clearField();
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Check the field");
        }
        
       
    }//GEN-LAST:event_jButton_saveActionPerformed

    private void jButton_loadStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loadStaffActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_jButton_loadStaffActionPerformed

    private void jButton_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_updateActionPerformed
        // TODO add your handling code here:
        String err="";
        if(jTextField_fullName.getText().equals("")||jTextField_address.getText().equals("")||jTextField_contactNo.getText().equals("")
             ||jTextField_combo.getText().equals("")||jTextField_bankAccNo.getText().equals("")||jTextField_basicSalary.getText().equals("")
                ||jTextField_contactNo.getText().equals("")||jTextField_dob.getDate().equals("")||jTextField_doj.getDate().equals(""))
        {
            err+="err";
        }
        if(err.equals(""))
        {
        Staff ob1=new Staff();
        /*
        int id=Integer.parseInt(jLabel9_id.getText());
        String fullName=jTextField_fullName.getText();
        String address=jTextField_address.getText();
        String dob=jTextField_dob.getText();
        String doj=jTextField_doj.getText();
        String designation=jComboBox_designation.getSelectedItem().toString();
        long contactNo=Long.parseLong(jTextField_contactNo.getText());
        long bankAccNo=Long.parseLong(jTextField_fullName.getText());
        double salary=Double.parseDouble(jTextField_address.getText());
        */
        
        SimpleDateFormat dFormat;
        SimpleDateFormat = dFormat =new SimpleDateFormat("yyyy-MM-dd");
        String dob=((String)dFormat.format(jTextField_dob.getDate())); 
        String doj=((String)dFormat.format(jTextField_doj.getDate()));
        
        
        ob1.setStaffId(Integer.parseInt(jLabel9_id.getText()));
        ob1.setFullName(jTextField_fullName.getText());
        ob1.setAddress(jTextField_address.getText());
        ob1.setDob(dob);
        ob1.setDoj(doj);
        ob1.setDesignation(jTextField_combo.getText().toString());
        ob1.setContactNo(Long.parseLong(jTextField_contactNo.getText()));
        ob1.setBankAccNo(Long.parseLong(jTextField_bankAccNo.getText()));
        double salary=Double.parseDouble(jTextField_basicSalary.getText());
        ob1.setBasicSalary(salary);
        
        
        /*
        ob1.setFullName(fullName);
        ob1.setAddress(address);
        ob1.setDob(dob);
        ob1.setDoj(doj);
        ob1.setDesignation(designation);
        ob1.setContactNo(contactNo);
        ob1.setBankAccNo(bankAccNo);
        ob1.setBasicSalary(salary);
        ob1.setStaffId(id);
        */
        StaffController sc=new StaffController();
        sc.updateStaff(ob1);
        loadData();
        clearField();
         }
        else
        {
            JOptionPane.showMessageDialog(null,"Check the field");
        }
    }//GEN-LAST:event_jButton_updateActionPerformed

    private void jTable_staffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_staffMouseClicked
        // TODO add your handling code here:
        //SimpleDateFormat dFormat;
        //SimpleDateFormat = dFormat =new SimpleDateFormat("yyyy-MM-dd");
       
        int row=jTable_staff.getSelectedRow();
        Date date = null;
       try {
           date = new SimpleDateFormat("yyyy-MM-dd").parse((String)jTable_staff.getValueAt(row, 3));
       } catch (ParseException ex) {
           Logger.getLogger(AddStaff.class.getName()).log(Level.SEVERE, null, ex);
       }
       
       Date date1 = null;
       try {
           date1 = new SimpleDateFormat("yyyy-MM-dd").parse((String)jTable_staff.getValueAt(row, 4));
       } catch (ParseException ex) {
           Logger.getLogger(AddStaff.class.getName()).log(Level.SEVERE, null, ex);
       }
          jTextField_dob.setDate(date); 
          jTextField_doj.setDate(date1);
        jLabel9_id.setText(jTable_staff.getValueAt(row,0).toString());
        jTextField_fullName.setText(jTable_staff.getValueAt(row, 1).toString());
        jTextField_address.setText(jTable_staff.getValueAt(row,2).toString());
        
        // jTextField_dob.setDate(jTable_staff.getValueAt(row, 3).toString());
       // jTextField_doj.setText((String)jTable_staff.getValueAt(row,4).toString());
        jTextField_combo.setText(jTable_staff.getValueAt(row,5).toString());
        jTextField_contactNo.setText(jTable_staff.getValueAt(row,6).toString());
        jTextField_bankAccNo.setText(jTable_staff.getValueAt(row, 7).toString());
        jTextField_basicSalary.setText(jTable_staff.getValueAt(row, 8).toString());
        jTextField_combo.setEditable(false);
    }//GEN-LAST:event_jTable_staffMouseClicked

    private void jButton_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_deleteActionPerformed
        // TODO add your handling code here:
        
         int id=Integer.parseInt(jLabel9_id.getText());
                
         
            StaffController sc=new StaffController();
        sc.deleteStaff(id);
        loadData();
        clearField();
               
        
    }//GEN-LAST:event_jButton_deleteActionPerformed

    private void jComboBox_designationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_designationActionPerformed
        // TODO add your handling code here:
        jTextField_combo.setText((java.lang.String) jComboBox_designation.getSelectedItem());
        jTextField_combo.setEditable(false);
    }//GEN-LAST:event_jComboBox_designationActionPerformed

    private void jTextField_contactNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_contactNoKeyTyped
        // TODO add your handling code here:
        char a= evt.getKeyChar();
        if(!(Character.isDigit(a))||(a == KeyEvent.VK_BACK_SPACE)||(a == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_contactNoKeyTyped

    private void jTextField_bankAccNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_bankAccNoKeyTyped
        // TODO add your handling code here:
        char a= evt.getKeyChar();
        if(!(Character.isDigit(a))||(a == KeyEvent.VK_BACK_SPACE)||(a == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_bankAccNoKeyTyped

    private void jTextField_basicSalaryKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_basicSalaryKeyTyped
        // TODO add your handling code here:
        char a= evt.getKeyChar();
        if(!(Character.isDigit(a))||(a == KeyEvent.VK_BACK_SPACE)||(a == KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_basicSalaryKeyTyped

    private void jButton_clearFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clearFieldActionPerformed
        // TODO add your handling code here:
        int count = jTable_staff.getRowCount();
        for(int i=0;i<count;i++)
        {
           model.removeRow(0);
        }
        clearField();
    }//GEN-LAST:event_jButton_clearFieldActionPerformed

    private void jTextField_fullNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_fullNameKeyTyped
        // TODO add your handling code here:
       char a=evt.getKeyChar();
        if((a>='0' && a<='9'))
        {
            evt.consume();
        }

        
    }//GEN-LAST:event_jTextField_fullNameKeyTyped

    private void jTextField_fullNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_fullNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_fullNameActionPerformed

    private void jTextField_contactNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_contactNoKeyReleased

        // TODO add your handling code here:
        String PATTERN="\\d{10}";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(jTextField_contactNo.getText());
        if(!match.matches())
        {
            jLabel_cerr.setText("Enter 10 digit mobile no.");
        }
        else
        {
            jLabel_cerr.setText("Phone number ok");
        }
    }//GEN-LAST:event_jTextField_contactNoKeyReleased

    private void jTextField_bankAccNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_bankAccNoKeyReleased
        // TODO add your handling code here:
        String PATTERN="\\d{13}";
        Pattern patt=Pattern.compile(PATTERN);
        Matcher match=patt.matcher(jTextField_bankAccNo.getText());
        if(!match.matches())
        {
            jLabel9.setText("Enter 13 digit bank acc no.");
        }
        else
        {
            jLabel9.setText("Bank Account Ok");
        }
    }//GEN-LAST:event_jTextField_bankAccNoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_clearField;
    private javax.swing.JButton jButton_delete;
    private javax.swing.JButton jButton_loadStaff;
    private javax.swing.JButton jButton_save;
    private javax.swing.JButton jButton_update;
    private javax.swing.JComboBox<String> jComboBox_designation;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel9_id;
    private javax.swing.JLabel jLabel_b;
    private javax.swing.JLabel jLabel_bank;
    private javax.swing.JLabel jLabel_cerr;
    private javax.swing.JLabel jLabel_cerror;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_staff;
    private javax.swing.JTextField jTextField_address;
    private javax.swing.JTextField jTextField_bankAccNo;
    private javax.swing.JTextField jTextField_basicSalary;
    private javax.swing.JTextField jTextField_combo;
    private javax.swing.JTextField jTextField_contactNo;
    private com.toedter.calendar.JDateChooser jTextField_dob;
    private com.toedter.calendar.JDateChooser jTextField_doj;
    private javax.swing.JTextField jTextField_fullName;
    // End of variables declaration//GEN-END:variables

 
   
}

    

