/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.staff.view;

import com.staff.controller.AttendanceController;
import com.staff.controller.StaffController;
import com.staff.model.Attendance;
import com.staff.model.Staff;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author sanja_000
 */
public class KeepAttendance extends javax.swing.JInternalFrame {

    DefaultTableModel model;
    private SimpleDateFormat SimpleDateFormat;
    /**
     * Creates new form KeepAttendance
     */
    public KeepAttendance() {
        initComponents();
        
         model = new DefaultTableModel(null,new String[]{"staffId","FullName","Date","Attendance"});
        jTable_attendance.setModel(model);
    }
    
     private void clearTable()
    {
        int count = jTable_attendance.getRowCount();
        for(int i=0;i<count;i++)
        {
           model.removeRow(0);
        }
        //clearField();
    }
     
     private void loadData()
    {
         clearTable();
        StaffController sc=new StaffController();
        ArrayList<Staff> list=sc.fetchData();
        SimpleDateFormat dFormat;
        SimpleDateFormat = dFormat =new SimpleDateFormat("yyyy-MM-dd");
        String date=dFormat.format(jDateChooser1.getDate()); 
        String[] a = {"Present","Absent"};
        JComboBox c = new JComboBox(a);
        String p="Present";
        for(int i=0;i<list.size();i++)
        {
            TableColumn col= jTable_attendance.getColumnModel().getColumn(3);
            col.setCellEditor(new DefaultCellEditor(c));
            model.addRow(new Object[]
            {
            list.get(i).getStaffId(),
            list.get(i).getFullName(),
           date,p
            });
             
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_attendance = new javax.swing.JTable();
        jButton_loadStaff = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton_Save = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setResizable(true);
        setTitle("Attendance Keeping");

        jLabel1.setText("Date");

        jTable_attendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable_attendance);

        jButton_loadStaff.setText("Load Staff");
        jButton_loadStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loadStaffActionPerformed(evt);
            }
        });

        jButton_Save.setText("Save");
        jButton_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SaveActionPerformed(evt);
            }
        });

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1)
                        .addGap(83, 83, 83)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jButton_loadStaff)
                        .addGap(32, 32, 32)
                        .addComponent(jButton_Save)
                        .addGap(27, 27, 27)
                        .addComponent(jButton1)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_loadStaff)
                    .addComponent(jButton_Save)
                    .addComponent(jButton1))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_loadStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loadStaffActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_jButton_loadStaffActionPerformed

    private void jButton_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SaveActionPerformed
        // TODO add your handling code here:
        
        ArrayList<Attendance> list=new ArrayList();
         int count=jTable_attendance.getRowCount();
         
         for(int i=0;i<count;i++)
        {
            Attendance ob=new Attendance();
            
            int staffId=Integer.parseInt(jTable_attendance.getValueAt(i,0).toString());
            String staffname=jTable_attendance.getValueAt(i,1).toString();
            
            String date=jTable_attendance.getValueAt(i,2).toString();
            String attendance=jTable_attendance.getValueAt(i,3).toString();
            
            //String d=new java.util.Date().toString();
            
            
            ob.setStaffId(staffId);
            ob.setStaffname(staffname);
            ob.setAttendancedate(date);
            ob.setAttendance(attendance);
           
            
            list.add(ob);
             
        }
        AttendanceController sdc=new AttendanceController();
        sdc.saveData(list);
        clearTable();
    }//GEN-LAST:event_jButton_SaveActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int count = jTable_attendance.getRowCount();
        for(int i=0;i<count;i++)
        {
           model.removeRow(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_Save;
    private javax.swing.JButton jButton_loadStaff;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_attendance;
    // End of variables declaration//GEN-END:variables

    private Object getColumn(int i) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
