/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.staff.view;

import javax.swing.JOptionPane;

/**
 *
 * @author sanja_000
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        jMenuItem_Logout.setEnabled(false);
        jMenuItem_staffRecord.setEnabled(false);
        jMenuItem_searchStaff.setEnabled(false);
        jMenuItem_keepAttendance.setEnabled(false);
        jMenuItem_viewAttendance.setEnabled(false);
        jMenuItem_keepSalary.setEnabled(false);
        jMenuItem_viewSalary.setEnabled(false);
        jMenuItem_userStatus.setEnabled(false);
        //jMenuItem_register.setEnabled(true);
        UserLogin ob=new UserLogin();
        ob.setLocation(400,200);
        DesktopPane.add(ob);
        ob.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        DesktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel_backgroundImage = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_Login = new javax.swing.JMenuItem();
        jMenuItem_Register = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem_staffRecord = new javax.swing.JMenuItem();
        jMenuItem_searchStaff = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem_keepAttendance = new javax.swing.JMenuItem();
        jMenuItem_viewAttendance = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem_keepSalary = new javax.swing.JMenuItem();
        jMenuItem_viewSalary = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem_userStatus = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("School Staff Management System");
        setMinimumSize(new java.awt.Dimension(1366, 765));
        setSize(new java.awt.Dimension(1366, 765));

        DesktopPane.setBackground(new java.awt.Color(51, 102, 0));
        DesktopPane.setForeground(new java.awt.Color(102, 153, 0));

        jPanel1.setBackground(new java.awt.Color(102, 153, 0));

        jLabel_backgroundImage.setIcon(new javax.swing.ImageIcon("D:\\Sanjaya\\Java Programming II\\SchoolStaffMgmtSystem\\college11.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_backgroundImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel_backgroundImage, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                .addContainerGap())
        );

        DesktopPane.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopPaneLayout = new javax.swing.GroupLayout(DesktopPane);
        DesktopPane.setLayout(DesktopPaneLayout);
        DesktopPaneLayout.setHorizontalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DesktopPaneLayout.setVerticalGroup(
            DesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(102, 255, 51));
        jMenuBar1.setForeground(new java.awt.Color(51, 204, 255));
        jMenuBar1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(1366, 768));

        jMenu1.setText("User Login");

        jMenuItem_Login.setText("Login");
        jMenuItem_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_LoginActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_Login);

        jMenuItem_Register.setText("Register");
        jMenuItem_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_RegisterActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_Register);

        jMenuItem_Logout.setText("  Logout");
        jMenuItem_Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem_LogoutMouseClicked(evt);
            }
        });
        jMenuItem_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_LogoutActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_Logout);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Staff Info");

        jMenuItem_staffRecord.setText("Add Staff Record");
        jMenuItem_staffRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_staffRecordActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_staffRecord);

        jMenuItem_searchStaff.setText("Search Staff");
        jMenuItem_searchStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_searchStaffActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem_searchStaff);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Attendace");

        jMenuItem_keepAttendance.setText("Keep Attendance Record");
        jMenuItem_keepAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_keepAttendanceActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_keepAttendance);

        jMenuItem_viewAttendance.setText("View Attendance");
        jMenuItem_viewAttendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_viewAttendanceActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem_viewAttendance);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Salary Detail");

        jMenuItem_keepSalary.setText("Keep Salary Record");
        jMenuItem_keepSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_keepSalaryActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_keepSalary);

        jMenuItem_viewSalary.setText("View Salary Report");
        jMenuItem_viewSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_viewSalaryActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem_viewSalary);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Status");

        jMenuItem_userStatus.setText("User Status");
        jMenuItem_userStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_userStatusActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem_userStatus);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_LoginActionPerformed
        // TODO add your handling code here:
        UserLogin ob=new UserLogin();
        ob.setLocation(440,150);
        DesktopPane.add(ob);
        ob.setVisible(true);
    }//GEN-LAST:event_jMenuItem_LoginActionPerformed

    private void jMenuItem_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_RegisterActionPerformed
        // TODO add your handling code here:
        Register ob=new Register();
        DesktopPane.add(ob);
        ob.setLocation(440,150);
        ob.setVisible(true);
    }//GEN-LAST:event_jMenuItem_RegisterActionPerformed

    private void jMenuItem_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_LogoutActionPerformed
        // TODO add your handling code here:
        
           DesktopPane.removeAll();
           DesktopPane.repaint();
           UserLogin ob1=new UserLogin();
        ob1.setLocation(400,200);
        DesktopPane.add(ob1);
        ob1.setVisible(true);
           
           MainFrame.jMenuItem_Logout.setEnabled(false);
           MainFrame.jMenuItem_Register.setEnabled(true);
           MainFrame.jMenuItem_Login.setEnabled(true);
           MainFrame.jMenuItem_searchStaff.setEnabled(false);
           MainFrame.jMenuItem_staffRecord.setEnabled(false);
           MainFrame.jMenuItem_keepAttendance.setEnabled(false);
           MainFrame.jMenuItem_viewAttendance.setEnabled(false);
           MainFrame.jMenuItem_keepSalary.setEnabled(false);
           MainFrame.jMenuItem_viewSalary.setEnabled(false);
           MainFrame.jMenuItem_userStatus.setEnabled(false);
           JOptionPane.showMessageDialog(null,"Logout Successfully");
           AddStaff ob=new AddStaff();
        //DesktopPane.add(ob);
        ob.dispose();
           
    }//GEN-LAST:event_jMenuItem_LogoutActionPerformed

    private void jMenuItem_staffRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_staffRecordActionPerformed
        // TODO add your handling code here:
        AddStaff ob=new AddStaff();
        DesktopPane.add(ob);
        ob.setVisible(true);
    }//GEN-LAST:event_jMenuItem_staffRecordActionPerformed

    private void jMenuItem_keepSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_keepSalaryActionPerformed
        // TODO add your handling code here:
         SalaryRecord ob=new SalaryRecord();
        DesktopPane.add(ob);
        ob.setLocation(300,70);
        ob.setVisible(true);
    }//GEN-LAST:event_jMenuItem_keepSalaryActionPerformed

    private void jMenuItem_searchStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_searchStaffActionPerformed
        // TODO add your handling code here:
        SearchStaff ob=new SearchStaff();
        DesktopPane.add(ob);
        ob.setVisible(true);
    }//GEN-LAST:event_jMenuItem_searchStaffActionPerformed

    private void jMenuItem_keepAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_keepAttendanceActionPerformed
        // TODO add your handling code here:
        KeepAttendance ob=new KeepAttendance();
        DesktopPane.add(ob);
        ob.setLocation(320,80);
        ob.setVisible(true);
    }//GEN-LAST:event_jMenuItem_keepAttendanceActionPerformed

    private void jMenuItem_viewAttendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_viewAttendanceActionPerformed
        // TODO add your handling code here:
        SearchAttendance ob=new SearchAttendance();
        DesktopPane.add(ob);
        ob.setLocation(340,90);
        ob.setVisible(true);
    }//GEN-LAST:event_jMenuItem_viewAttendanceActionPerformed

    private void jMenuItem_LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem_LogoutMouseClicked
        // TODO add your handling code here:
        AddStaff ob=new AddStaff();
        DesktopPane.add(ob);
        ob.dispose();
    }//GEN-LAST:event_jMenuItem_LogoutMouseClicked

    private void jMenuItem_viewSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_viewSalaryActionPerformed
        // TODO add your handling code here:
        SalaryReport ob=new SalaryReport();
        DesktopPane.add(ob);
        ob.setLocation(340,90);
        ob.setVisible(true);
    }//GEN-LAST:event_jMenuItem_viewSalaryActionPerformed

    private void jMenuItem_userStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_userStatusActionPerformed
        // TODO add your handling code here:
        UserStatus ob=new UserStatus();
        DesktopPane.add(ob);
        ob.setLocation(380,90);
        ob.setVisible(true);
    }//GEN-LAST:event_jMenuItem_userStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JLabel jLabel_backgroundImage;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem6;
    public static javax.swing.JMenuItem jMenuItem_Login;
    public static final javax.swing.JMenuItem jMenuItem_Logout = new javax.swing.JMenuItem();
    public static javax.swing.JMenuItem jMenuItem_Register;
    public static javax.swing.JMenuItem jMenuItem_keepAttendance;
    public static javax.swing.JMenuItem jMenuItem_keepSalary;
    public static javax.swing.JMenuItem jMenuItem_searchStaff;
    public static javax.swing.JMenuItem jMenuItem_staffRecord;
    public static javax.swing.JMenuItem jMenuItem_userStatus;
    public static javax.swing.JMenuItem jMenuItem_viewAttendance;
    public static javax.swing.JMenuItem jMenuItem_viewSalary;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
