/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.staff.view;

import com.staff.controller.SalaryController;
import com.staff.model.Salary;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sanja_000
 */
public class SalaryRecord extends javax.swing.JInternalFrame {

    DefaultTableModel model;
    private SimpleDateFormat SimpleDateFormat;
    /**
     * Creates new form SalaryRecord
     */
    public SalaryRecord() {
        initComponents();
        
        model = new DefaultTableModel(null,new String[]{"FullName","Date","Bonus","BasicSalary","StaffId"});
        jTable_keepSalary.setModel(model);
    }
    
    private void clearTable()
    {
        int count = jTable_keepSalary.getRowCount();
        for(int i=0;i<count;i++)
        {
           model.removeRow(0);
        }
        //clearField();
    }
    
    private void loadData()
    {
         clearTable();
        SalaryController sc=new SalaryController();
        ArrayList<Salary> list=sc.fetchData();
        SimpleDateFormat dFormat;
        SimpleDateFormat = dFormat =new SimpleDateFormat("yyyy-MM-dd");
        String date=dFormat.format(jDateChooser1.getDate()); 
        String[] a = {"Present","Absent"};
        JComboBox c = new JComboBox(a);
        String p="Present";
        
        for(int i=0;i<list.size();i++)
        {
            //TableColumn col= jTable_keepSalary.getColumnModel().getColumn(3);
            //col.setCellEditor(new DefaultCellEditor(c));
            model.addRow(new Object[]
            {
            list.get(i).getStaffName(),
           date,
           list.get(i).getBonus(),
           list.get(i).getBasicSalary(),
           list.get(i).getStaffId()
           
            });
             
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_keepSalary = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton_loadStaff = new javax.swing.JButton();
        jButton_saveSalary = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Keep Salary Record");

        jDateChooser1.setMaxSelectableDate(new java.util.Date(1546197409000L));
        jDateChooser1.setMinSelectableDate(new java.util.Date(1420053409000L));

        jTable_keepSalary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable_keepSalary);

        jLabel1.setText("Date");

        jButton_loadStaff.setText("Load Staff");
        jButton_loadStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loadStaffActionPerformed(evt);
            }
        });

        jButton_saveSalary.setText("Save");
        jButton_saveSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveSalaryActionPerformed(evt);
            }
        });

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jButton_loadStaff)
                        .addGap(97, 97, 97)
                        .addComponent(jButton_saveSalary)
                        .addGap(74, 74, 74)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(39, 39, 39)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 20, Short.MAX_VALUE)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_loadStaff)
                    .addComponent(jButton_saveSalary)
                    .addComponent(jButton1))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_loadStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loadStaffActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_jButton_loadStaffActionPerformed

    private void jButton_saveSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveSalaryActionPerformed
        // TODO add your handling code here:
        ArrayList<Salary> list=new ArrayList();
        int count=jTable_keepSalary.getRowCount();

        for(int i=0;i<count;i++)
        {
            Salary ob=new Salary();
            String staffname=jTable_keepSalary.getValueAt(i,0).toString();
            String date=jTable_keepSalary.getValueAt(i,1).toString();
            double bonus=Double.parseDouble(jTable_keepSalary.getValueAt(i,2).toString());
            double bsalary=Double.parseDouble(jTable_keepSalary.getValueAt(i,3).toString());
            int staffId=Integer.parseInt(jTable_keepSalary.getValueAt(i,4).toString());
            //String d=new java.util.Date().toString();

            ob.setStaffId(staffId);
            ob.setStaffName(staffname);
            ob.setSalaryPaidDate(date);
            ob.setBonus(bonus);
            ob.setBasicSalary(bsalary);

            list.add(ob);
            
            
    }//GEN-LAST:event_jButton_saveSalaryActionPerformed
            SalaryController sc=new SalaryController();
            sc.saveData(list);
            clearTable();
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int count = jTable_keepSalary.getRowCount();
        for(int i=0;i<count;i++)
        {
           model.removeRow(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_loadStaff;
    private javax.swing.JButton jButton_saveSalary;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_keepSalary;
    // End of variables declaration//GEN-END:variables
}
