/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.staff.view;

import com.staff.controller.LoginController;
import com.staff.model.Login;
import javax.swing.JOptionPane;

/**
 *
 * @author sanja_000
 */
public class UserLogin extends javax.swing.JInternalFrame {

    /**
     * Creates new form UserLogin
     */
    public UserLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField_password = new javax.swing.JPasswordField();
        jTextField_username = new javax.swing.JTextField();
        jButton_login = new javax.swing.JButton();

        setClosable(true);
        setTitle("UserLogin");

        jPanel1.setBackground(new java.awt.Color(0, 204, 0));

        jLabel1.setText("Username");

        jLabel2.setText("Password");

        jPasswordField_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_passwordActionPerformed(evt);
            }
        });

        jButton_login.setText("Login");
        jButton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_login)
                            .addComponent(jPasswordField_password))))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jButton_login)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_passwordActionPerformed

    private void jButton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loginActionPerformed
        // TODO add your handling code here:
        Login ob=new Login();
        ob.setUsername(jTextField_username.getText());
        ob.setPassword(jPasswordField_password.getText());
        LoginController lc=new LoginController();
        int status=lc.userLogin(ob);
        if(status==-1)
        {
            JOptionPane.showMessageDialog(null,"Invalid username");
        }
        else if(status==0)//Normal user
        {
           JOptionPane.showMessageDialog(null,"Logged in as Staff"); 
           MainFrame.jMenuItem_Logout.setEnabled(true);
           MainFrame.jMenuItem_Register.setEnabled(false);
           MainFrame.jMenuItem_searchStaff.setEnabled(true);
           MainFrame.jMenuItem_staffRecord.setEnabled(false);
           MainFrame.jMenuItem_keepAttendance.setEnabled(false);
           MainFrame.jMenuItem_viewAttendance.setEnabled(true);
            MainFrame.jMenuItem_keepSalary.setEnabled(false);
           MainFrame.jMenuItem_viewSalary.setEnabled(true);
           MainFrame.jMenuItem_userStatus.setEnabled(false);

           MainFrame.jMenuItem_Login.setEnabled(false);
           dispose();
        }
        else if(status==1) //for admin
        {
            JOptionPane.showMessageDialog(null,"Logged in as Admin");
            MainFrame.jMenuItem_Logout.setEnabled(true);
            MainFrame.jMenuItem_staffRecord.setEnabled(true);
            MainFrame.jMenuItem_Register.setEnabled(false);
           MainFrame.jMenuItem_searchStaff.setEnabled(true);
           MainFrame.jMenuItem_Login.setEnabled(false);
            MainFrame.jMenuItem_keepAttendance.setEnabled(true);
           MainFrame.jMenuItem_viewAttendance.setEnabled(true);
            MainFrame.jMenuItem_keepSalary.setEnabled(true);
           MainFrame.jMenuItem_viewSalary.setEnabled(true);
           MainFrame.jMenuItem_userStatus.setEnabled(true);

           dispose();
        }
    }//GEN-LAST:event_jButton_loginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration//GEN-END:variables
}
